#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Phần_mềm_QLĐ
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="QLD")]
	public partial class QLDDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertHocKy(HocKy instance);
    partial void UpdateHocKy(HocKy instance);
    partial void DeleteHocKy(HocKy instance);
    partial void InsertLop(Lop instance);
    partial void UpdateLop(Lop instance);
    partial void DeleteLop(Lop instance);
    partial void InsertMonHP(MonHP instance);
    partial void UpdateMonHP(MonHP instance);
    partial void DeleteMonHP(MonHP instance);
    partial void InsertSinhVien(SinhVien instance);
    partial void UpdateSinhVien(SinhVien instance);
    partial void DeleteSinhVien(SinhVien instance);
    #endregion
		
		public QLDDataContext() : 
				base(global::Phần_mềm_QLĐ.Properties.Settings.Default.QLDConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public QLDDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLDDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLDDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLDDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<DiemHP> DiemHPs
		{
			get
			{
				return this.GetTable<DiemHP>();
			}
		}
		
		public System.Data.Linq.Table<HocKy> HocKies
		{
			get
			{
				return this.GetTable<HocKy>();
			}
		}
		
		public System.Data.Linq.Table<Lop> Lops
		{
			get
			{
				return this.GetTable<Lop>();
			}
		}
		
		public System.Data.Linq.Table<MonHP> MonHPs
		{
			get
			{
				return this.GetTable<MonHP>();
			}
		}
		
		public System.Data.Linq.Table<SinhVien> SinhViens
		{
			get
			{
				return this.GetTable<SinhVien>();
			}
		}
		
		public System.Data.Linq.Table<DangNhap> DangNhaps
		{
			get
			{
				return this.GetTable<DangNhap>();
			}
		}
		
		public System.Data.Linq.Table<Ketqua> Ketquas
		{
			get
			{
				return this.GetTable<Ketqua>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.BangdiemHP")]
		public ISingleResult<BangdiemHPResult> BangdiemHP([global::System.Data.Linq.Mapping.ParameterAttribute(Name="MaLop", DbType="NVarChar(50)")] string maLop, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MaHP", DbType="NVarChar(50)")] string maHP)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maLop, maHP);
			return ((ISingleResult<BangdiemHPResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.DiemHP_Insert")]
		public int DiemHP_Insert([global::System.Data.Linq.Mapping.ParameterAttribute(Name="MaHP", DbType="NVarChar(50)")] string maHP, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MaSV", DbType="NVarChar(50)")] string maSV)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maHP, maSV);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.DiemHP_Search")]
		public ISingleResult<DiemHP_SearchResult> DiemHP_Search([global::System.Data.Linq.Mapping.ParameterAttribute(Name="MaHP", DbType="NVarChar(50)")] string maHP, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MaSV", DbType="NVarChar(50)")] string maSV)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maHP, maSV);
			return ((ISingleResult<DiemHP_SearchResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.DiemHP_UpdateLan1")]
		public int DiemHP_UpdateLan1([global::System.Data.Linq.Mapping.ParameterAttribute(Name="DiemCC", DbType="Float")] System.Nullable<double> diemCC, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MaHP", DbType="NVarChar(50)")] string maHP, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MaSV", DbType="NVarChar(50)")] string maSV)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), diemCC, maHP, maSV);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.DiemHP_UpdateLan3")]
		public int DiemHP_UpdateLan3([global::System.Data.Linq.Mapping.ParameterAttribute(Name="DiemCK", DbType="Float")] System.Nullable<double> diemCK, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MaHP", DbType="NVarChar(50)")] string maHP, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MaSV", DbType="NVarChar(50)")] string maSV)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), diemCK, maHP, maSV);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.DiemHP_UpdateLan2")]
		public int DiemHP_UpdateLan2([global::System.Data.Linq.Mapping.ParameterAttribute(Name="DiemGK", DbType="Float")] System.Nullable<double> diemGK, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MaHP", DbType="NVarChar(50)")] string maHP, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MaSV", DbType="NVarChar(50)")] string maSV)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), diemGK, maHP, maSV);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.HocKy_Delete")]
		public int HocKy_Delete([global::System.Data.Linq.Mapping.ParameterAttribute(Name="MaHocKy", DbType="NVarChar(50)")] string maHocKy)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maHocKy);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.HocKy_Insert")]
		public int HocKy_Insert([global::System.Data.Linq.Mapping.ParameterAttribute(Name="MaHocKy", DbType="NVarChar(50)")] string maHocKy, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TenHocKy", DbType="NVarChar(100)")] string tenHocKy)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maHocKy, tenHocKy);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.HocKy_SelectAll")]
		public ISingleResult<HocKy_SelectAllResult> HocKy_SelectAll()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<HocKy_SelectAllResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.HocKy_Update")]
		public int HocKy_Update([global::System.Data.Linq.Mapping.ParameterAttribute(Name="MaHocKy", DbType="NVarChar(50)")] string maHocKy, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TenHocKy", DbType="NVarChar(100)")] string tenHocKy)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maHocKy, tenHocKy);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Lops_Delete")]
		public int Lops_Delete([global::System.Data.Linq.Mapping.ParameterAttribute(Name="MaLop", DbType="NVarChar(50)")] string maLop)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maLop);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Lops_SelectAll")]
		public ISingleResult<Lops_SelectAllResult> Lops_SelectAll()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<Lops_SelectAllResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.MonHP_Delete")]
		public int MonHP_Delete([global::System.Data.Linq.Mapping.ParameterAttribute(Name="MaHP", DbType="NVarChar(50)")] string maHP)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maHP);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.MonHP_Insert")]
		public int MonHP_Insert([global::System.Data.Linq.Mapping.ParameterAttribute(Name="MaHP", DbType="NVarChar(50)")] string maHP, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TenHP", DbType="NVarChar(100)")] string tenHP, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SoTinChi", DbType="Int")] System.Nullable<int> soTinChi, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MaHocKy", DbType="NVarChar(50)")] string maHocKy)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maHP, tenHP, soTinChi, maHocKy);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.MonHP_SelectAll")]
		public ISingleResult<MonHP_SelectAllResult> MonHP_SelectAll()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<MonHP_SelectAllResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.MonHP_SelectMaHocKy")]
		public ISingleResult<MonHP_SelectMaHocKyResult> MonHP_SelectMaHocKy([global::System.Data.Linq.Mapping.ParameterAttribute(Name="MaHocKy", DbType="NVarChar(50)")] string maHocKy)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maHocKy);
			return ((ISingleResult<MonHP_SelectMaHocKyResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.MonHP_Update")]
		public int MonHP_Update([global::System.Data.Linq.Mapping.ParameterAttribute(Name="MaHP", DbType="NVarChar(50)")] string maHP, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TenHP", DbType="NVarChar(100)")] string tenHP, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SoTinChi", DbType="Int")] System.Nullable<int> soTinChi)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maHP, tenHP, soTinChi);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SinhVien_Delete")]
		public int SinhVien_Delete([global::System.Data.Linq.Mapping.ParameterAttribute(Name="MaSV", DbType="NVarChar(50)")] string maSV)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maSV);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SinhVien_Insert", IsComposable=true)]
		public object SinhVien_Insert([global::System.Data.Linq.Mapping.ParameterAttribute(Name="MaSV", DbType="NVarChar(50)")] string maSV, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="HoTen", DbType="NChar(50)")] string hoTen, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NgaySinh", DbType="DateTime")] System.Nullable<System.DateTime> ngaySinh, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="GioiTinh", DbType="Int")] System.Nullable<int> gioiTinh, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DanToc", DbType="NVarChar(50)")] string danToc, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NoiSinh", DbType="NVarChar(100)")] string noiSinh, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MaLop", DbType="NVarChar(50)")] string maLop)
		{
			return ((object)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maSV, hoTen, ngaySinh, gioiTinh, danToc, noiSinh, maLop).ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SinhVien_Search")]
		public ISingleResult<SinhVien_SearchResult> SinhVien_Search([global::System.Data.Linq.Mapping.ParameterAttribute(Name="HoTen", DbType="NChar(50)")] string hoTen, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MaLop", DbType="NVarChar(50)")] string maLop)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), hoTen, maLop);
			return ((ISingleResult<SinhVien_SearchResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SinhVien_SelectAll")]
		public ISingleResult<SinhVien_SelectAllResult> SinhVien_SelectAll()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<SinhVien_SelectAllResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SinhVien_selectMalop")]
		public ISingleResult<SinhVien_selectMalopResult> SinhVien_selectMalop([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string malop)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), malop);
			return ((ISingleResult<SinhVien_selectMalopResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SinhVien_Update")]
		public int SinhVien_Update([global::System.Data.Linq.Mapping.ParameterAttribute(Name="MaSV", DbType="NVarChar(50)")] string maSV, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="HoTen", DbType="NChar(50)")] string hoTen, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NgaySinh", DbType="DateTime")] System.Nullable<System.DateTime> ngaySinh, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="GioiTinh", DbType="Int")] System.Nullable<int> gioiTinh, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DanToc", DbType="NVarChar(50)")] string danToc, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NoiSinh", DbType="NVarChar(100)")] string noiSinh)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maSV, hoTen, ngaySinh, gioiTinh, danToc, noiSinh);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Lops_Insert")]
		public int Lops_Insert([global::System.Data.Linq.Mapping.ParameterAttribute(Name="MaLop", DbType="NVarChar(50)")] string maLop, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TenLop", DbType="NVarChar(100)")] string tenLop, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="GiaoVienChuNhiem", DbType="NVarChar(50)")] string giaoVienChuNhiem, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Khoa", DbType="NVarChar(50)")] string khoa)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maLop, tenLop, giaoVienChuNhiem, khoa);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Lop_Update")]
		public int Lop_Update([global::System.Data.Linq.Mapping.ParameterAttribute(Name="MaLop", DbType="NVarChar(50)")] string maLop, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TenLop", DbType="NVarChar(100)")] string tenLop, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="GiaoVienChuNhiem", DbType="NVarChar(50)")] string giaoVienChuNhiem, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Khoa", DbType="NVarChar(50)")] string khoa)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maLop, tenLop, giaoVienChuNhiem, khoa);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Sinhvien_selectMalops")]
		public ISingleResult<Sinhvien_selectMalopsResult> Sinhvien_selectMalops()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<Sinhvien_selectMalopsResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Sinhvien_Deletes")]
		public int Sinhvien_Deletes([global::System.Data.Linq.Mapping.ParameterAttribute(Name="MaSV", DbType="NVarChar(50)")] string maSV)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maSV);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Sinhvien_Updates")]
		public int Sinhvien_Updates([global::System.Data.Linq.Mapping.ParameterAttribute(Name="MaSV", DbType="NVarChar(50)")] string maSV, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="HoTen", DbType="NChar(50)")] string hoTen, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NgaySinh", DbType="DateTime")] System.Nullable<System.DateTime> ngaySinh, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="GioiTinh", DbType="Int")] System.Nullable<int> gioiTinh, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DanToc", DbType="NVarChar(50)")] string danToc, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NoiSinh", DbType="NVarChar(100)")] string noiSinh, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Email", DbType="NVarChar(50)")] string email, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Sdt", DbType="NVarChar(50)")] string sdt, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DiaChi", DbType="NVarChar(50)")] string diaChi)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maSV, hoTen, ngaySinh, gioiTinh, danToc, noiSinh, email, sdt, diaChi);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Sinhvien_Inserts")]
		public int Sinhvien_Inserts([global::System.Data.Linq.Mapping.ParameterAttribute(Name="MaSV", DbType="NVarChar(50)")] string maSV, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="HoTen", DbType="NChar(50)")] string hoTen, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NgaySinh", DbType="DateTime")] System.Nullable<System.DateTime> ngaySinh, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="GioiTinh", DbType="Int")] System.Nullable<int> gioiTinh, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DanToc", DbType="NVarChar(50)")] string danToc, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NoiSinh", DbType="NVarChar(100)")] string noiSinh, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MaLop", DbType="NVarChar(50)")] string maLop, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Email", DbType="NVarChar(50)")] string email, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Sdt", DbType="NVarChar(50)")] string sdt, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DiaChi", DbType="NVarChar(50)")] string diaChi)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maSV, hoTen, ngaySinh, gioiTinh, danToc, noiSinh, maLop, email, sdt, diaChi);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Sinhvien_Updatess")]
		public int Sinhvien_Updatess([global::System.Data.Linq.Mapping.ParameterAttribute(Name="MaSV", DbType="NVarChar(50)")] string maSV, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="HoTen", DbType="NChar(50)")] string hoTen, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MaLop", DbType="NVarChar(50)")] string maLop, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NgaySinh", DbType="DateTime")] System.Nullable<System.DateTime> ngaySinh, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="GioiTinh", DbType="Int")] System.Nullable<int> gioiTinh, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DanToc", DbType="NVarChar(50)")] string danToc, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NoiSinh", DbType="NVarChar(100)")] string noiSinh)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maSV, hoTen, maLop, ngaySinh, gioiTinh, danToc, noiSinh);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Sinhvien_Insertsss")]
		public int Sinhvien_Insertsss([global::System.Data.Linq.Mapping.ParameterAttribute(Name="MaSV", DbType="NVarChar(50)")] string maSV, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="HoTen", DbType="NChar(50)")] string hoTen, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NgaySinh", DbType="DateTime")] System.Nullable<System.DateTime> ngaySinh, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="GioiTinh", DbType="Int")] System.Nullable<int> gioiTinh, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DanToc", DbType="NVarChar(50)")] string danToc, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NoiSinh", DbType="NVarChar(100)")] string noiSinh, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MaLop", DbType="NVarChar(50)")] string maLop, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Email", DbType="NVarChar(50)")] string email, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Sdt", DbType="NVarChar(50)")] string sdt, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DiaChi", DbType="NVarChar(50)")] string diaChi)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maSV, hoTen, ngaySinh, gioiTinh, danToc, noiSinh, maLop, email, sdt, diaChi);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Sinhvien_Updatesss")]
		public int Sinhvien_Updatesss([global::System.Data.Linq.Mapping.ParameterAttribute(Name="MaSV", DbType="NVarChar(50)")] string maSV, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="HoTen", DbType="NChar(50)")] string hoTen, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MaLop", DbType="NVarChar(50)")] string maLop, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NgaySinh", DbType="DateTime")] System.Nullable<System.DateTime> ngaySinh, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="GioiTinh", DbType="Int")] System.Nullable<int> gioiTinh, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DanToc", DbType="NVarChar(50)")] string danToc, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NoiSinh", DbType="NVarChar(100)")] string noiSinh, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Email", DbType="NVarChar(50)")] string email, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Sdt", DbType="NVarChar(50)")] string sdt, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DiaChi", DbType="NVarChar(50)")] string diaChi)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maSV, hoTen, maLop, ngaySinh, gioiTinh, danToc, noiSinh, email, sdt, diaChi);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Sinhvien_Updatessss")]
		public int Sinhvien_Updatessss([global::System.Data.Linq.Mapping.ParameterAttribute(Name="MaSV", DbType="NVarChar(50)")] string maSV, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="HoTen", DbType="NChar(50)")] string hoTen, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MaLop", DbType="NVarChar(50)")] string maLop, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NgaySinh", DbType="DateTime")] System.Nullable<System.DateTime> ngaySinh, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="GioiTinh", DbType="Int")] System.Nullable<int> gioiTinh, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DanToc", DbType="NVarChar(50)")] string danToc, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NoiSinh", DbType="NVarChar(100)")] string noiSinh, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Email", DbType="NVarChar(50)")] string email, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Sdt", DbType="NVarChar(50)")] string sdt, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DiaChi", DbType="NVarChar(50)")] string diaChi)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maSV, hoTen, maLop, ngaySinh, gioiTinh, danToc, noiSinh, email, sdt, diaChi);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Sinhvien_Updatenew")]
		public int Sinhvien_Updatenew([global::System.Data.Linq.Mapping.ParameterAttribute(Name="MaSV", DbType="NVarChar(50)")] string maSV, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="HoTen", DbType="NChar(50)")] string hoTen, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NgaySinh", DbType="DateTime")] System.Nullable<System.DateTime> ngaySinh, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="GioiTinh", DbType="Int")] System.Nullable<int> gioiTinh, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DanToc", DbType="NVarChar(50)")] string danToc, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NoiSinh", DbType="NVarChar(100)")] string noiSinh, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Email", DbType="NVarChar(50)")] string email, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Sdt", DbType="NVarChar(50)")] string sdt, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DiaChi", DbType="NVarChar(50)")] string diaChi)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maSV, hoTen, ngaySinh, gioiTinh, danToc, noiSinh, email, sdt, diaChi);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Sinhvien_selectMasv")]
		public ISingleResult<Sinhvien_selectMasvResult> Sinhvien_selectMasv([global::System.Data.Linq.Mapping.ParameterAttribute(Name="MaSV", DbType="NVarChar(50)")] string maSV)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maSV);
			return ((ISingleResult<Sinhvien_selectMasvResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ketqua_selectAll")]
		public ISingleResult<ketqua_selectAllResult> ketqua_selectAll()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<ketqua_selectAllResult>)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DiemHP")]
	public partial class DiemHP
	{
		
		private string _MaSV;
		
		private string _MaHP;
		
		private System.Nullable<double> _DiemCC;
		
		private System.Nullable<double> _DiemGK;
		
		private System.Nullable<double> _DiemCK;
		
		public DiemHP()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaSV", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string MaSV
		{
			get
			{
				return this._MaSV;
			}
			set
			{
				if ((this._MaSV != value))
				{
					this._MaSV = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaHP", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string MaHP
		{
			get
			{
				return this._MaHP;
			}
			set
			{
				if ((this._MaHP != value))
				{
					this._MaHP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiemCC", DbType="Float")]
		public System.Nullable<double> DiemCC
		{
			get
			{
				return this._DiemCC;
			}
			set
			{
				if ((this._DiemCC != value))
				{
					this._DiemCC = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiemGK", DbType="Float")]
		public System.Nullable<double> DiemGK
		{
			get
			{
				return this._DiemGK;
			}
			set
			{
				if ((this._DiemGK != value))
				{
					this._DiemGK = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiemCK", DbType="Float")]
		public System.Nullable<double> DiemCK
		{
			get
			{
				return this._DiemCK;
			}
			set
			{
				if ((this._DiemCK != value))
				{
					this._DiemCK = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.HocKy")]
	public partial class HocKy : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaHocKy;
		
		private string _TenHocKy;
		
		private EntitySet<MonHP> _MonHPs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaHocKyChanging(string value);
    partial void OnMaHocKyChanged();
    partial void OnTenHocKyChanging(string value);
    partial void OnTenHocKyChanged();
    #endregion
		
		public HocKy()
		{
			this._MonHPs = new EntitySet<MonHP>(new Action<MonHP>(this.attach_MonHPs), new Action<MonHP>(this.detach_MonHPs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaHocKy", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaHocKy
		{
			get
			{
				return this._MaHocKy;
			}
			set
			{
				if ((this._MaHocKy != value))
				{
					this.OnMaHocKyChanging(value);
					this.SendPropertyChanging();
					this._MaHocKy = value;
					this.SendPropertyChanged("MaHocKy");
					this.OnMaHocKyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenHocKy", DbType="NVarChar(100)")]
		public string TenHocKy
		{
			get
			{
				return this._TenHocKy;
			}
			set
			{
				if ((this._TenHocKy != value))
				{
					this.OnTenHocKyChanging(value);
					this.SendPropertyChanging();
					this._TenHocKy = value;
					this.SendPropertyChanged("TenHocKy");
					this.OnTenHocKyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HocKy_MonHP", Storage="_MonHPs", ThisKey="MaHocKy", OtherKey="MaHocKy")]
		public EntitySet<MonHP> MonHPs
		{
			get
			{
				return this._MonHPs;
			}
			set
			{
				this._MonHPs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_MonHPs(MonHP entity)
		{
			this.SendPropertyChanging();
			entity.HocKy = this;
		}
		
		private void detach_MonHPs(MonHP entity)
		{
			this.SendPropertyChanging();
			entity.HocKy = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Lops")]
	public partial class Lop : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaLop;
		
		private string _TenLop;
		
		private string _GiaoVienChuNhiem;
		
		private string _Khoa;
		
		private EntitySet<SinhVien> _SinhViens;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaLopChanging(string value);
    partial void OnMaLopChanged();
    partial void OnTenLopChanging(string value);
    partial void OnTenLopChanged();
    partial void OnGiaoVienChuNhiemChanging(string value);
    partial void OnGiaoVienChuNhiemChanged();
    partial void OnKhoaChanging(string value);
    partial void OnKhoaChanged();
    #endregion
		
		public Lop()
		{
			this._SinhViens = new EntitySet<SinhVien>(new Action<SinhVien>(this.attach_SinhViens), new Action<SinhVien>(this.detach_SinhViens));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaLop", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaLop
		{
			get
			{
				return this._MaLop;
			}
			set
			{
				if ((this._MaLop != value))
				{
					this.OnMaLopChanging(value);
					this.SendPropertyChanging();
					this._MaLop = value;
					this.SendPropertyChanged("MaLop");
					this.OnMaLopChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenLop", DbType="NVarChar(100)")]
		public string TenLop
		{
			get
			{
				return this._TenLop;
			}
			set
			{
				if ((this._TenLop != value))
				{
					this.OnTenLopChanging(value);
					this.SendPropertyChanging();
					this._TenLop = value;
					this.SendPropertyChanged("TenLop");
					this.OnTenLopChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GiaoVienChuNhiem", DbType="NVarChar(50)")]
		public string GiaoVienChuNhiem
		{
			get
			{
				return this._GiaoVienChuNhiem;
			}
			set
			{
				if ((this._GiaoVienChuNhiem != value))
				{
					this.OnGiaoVienChuNhiemChanging(value);
					this.SendPropertyChanging();
					this._GiaoVienChuNhiem = value;
					this.SendPropertyChanged("GiaoVienChuNhiem");
					this.OnGiaoVienChuNhiemChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Khoa", DbType="NVarChar(50)")]
		public string Khoa
		{
			get
			{
				return this._Khoa;
			}
			set
			{
				if ((this._Khoa != value))
				{
					this.OnKhoaChanging(value);
					this.SendPropertyChanging();
					this._Khoa = value;
					this.SendPropertyChanged("Khoa");
					this.OnKhoaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Lop_SinhVien", Storage="_SinhViens", ThisKey="MaLop", OtherKey="MaLop")]
		public EntitySet<SinhVien> SinhViens
		{
			get
			{
				return this._SinhViens;
			}
			set
			{
				this._SinhViens.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_SinhViens(SinhVien entity)
		{
			this.SendPropertyChanging();
			entity.Lop = this;
		}
		
		private void detach_SinhViens(SinhVien entity)
		{
			this.SendPropertyChanging();
			entity.Lop = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MonHP")]
	public partial class MonHP : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaHP;
		
		private string _TenHP;
		
		private System.Nullable<int> _SoTinChi;
		
		private string _MaHocKy;
		
		private EntityRef<HocKy> _HocKy;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaHPChanging(string value);
    partial void OnMaHPChanged();
    partial void OnTenHPChanging(string value);
    partial void OnTenHPChanged();
    partial void OnSoTinChiChanging(System.Nullable<int> value);
    partial void OnSoTinChiChanged();
    partial void OnMaHocKyChanging(string value);
    partial void OnMaHocKyChanged();
    #endregion
		
		public MonHP()
		{
			this._HocKy = default(EntityRef<HocKy>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaHP", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaHP
		{
			get
			{
				return this._MaHP;
			}
			set
			{
				if ((this._MaHP != value))
				{
					this.OnMaHPChanging(value);
					this.SendPropertyChanging();
					this._MaHP = value;
					this.SendPropertyChanged("MaHP");
					this.OnMaHPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenHP", DbType="NVarChar(100)")]
		public string TenHP
		{
			get
			{
				return this._TenHP;
			}
			set
			{
				if ((this._TenHP != value))
				{
					this.OnTenHPChanging(value);
					this.SendPropertyChanging();
					this._TenHP = value;
					this.SendPropertyChanged("TenHP");
					this.OnTenHPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoTinChi", DbType="Int")]
		public System.Nullable<int> SoTinChi
		{
			get
			{
				return this._SoTinChi;
			}
			set
			{
				if ((this._SoTinChi != value))
				{
					this.OnSoTinChiChanging(value);
					this.SendPropertyChanging();
					this._SoTinChi = value;
					this.SendPropertyChanged("SoTinChi");
					this.OnSoTinChiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaHocKy", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string MaHocKy
		{
			get
			{
				return this._MaHocKy;
			}
			set
			{
				if ((this._MaHocKy != value))
				{
					if (this._HocKy.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaHocKyChanging(value);
					this.SendPropertyChanging();
					this._MaHocKy = value;
					this.SendPropertyChanged("MaHocKy");
					this.OnMaHocKyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HocKy_MonHP", Storage="_HocKy", ThisKey="MaHocKy", OtherKey="MaHocKy", IsForeignKey=true)]
		public HocKy HocKy
		{
			get
			{
				return this._HocKy.Entity;
			}
			set
			{
				HocKy previousValue = this._HocKy.Entity;
				if (((previousValue != value) 
							|| (this._HocKy.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._HocKy.Entity = null;
						previousValue.MonHPs.Remove(this);
					}
					this._HocKy.Entity = value;
					if ((value != null))
					{
						value.MonHPs.Add(this);
						this._MaHocKy = value.MaHocKy;
					}
					else
					{
						this._MaHocKy = default(string);
					}
					this.SendPropertyChanged("HocKy");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SinhVien")]
	public partial class SinhVien : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaSV;
		
		private string _HoTen;
		
		private System.Nullable<System.DateTime> _NgaySinh;
		
		private System.Nullable<int> _GioiTinh;
		
		private string _DanToc;
		
		private string _NoiSinh;
		
		private string _MaLop;
		
		private string _Email;
		
		private string _Sdt;
		
		private string _DiaChi;
		
		private EntityRef<Lop> _Lop;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaSVChanging(string value);
    partial void OnMaSVChanged();
    partial void OnHoTenChanging(string value);
    partial void OnHoTenChanged();
    partial void OnNgaySinhChanging(System.Nullable<System.DateTime> value);
    partial void OnNgaySinhChanged();
    partial void OnGioiTinhChanging(System.Nullable<int> value);
    partial void OnGioiTinhChanged();
    partial void OnDanTocChanging(string value);
    partial void OnDanTocChanged();
    partial void OnNoiSinhChanging(string value);
    partial void OnNoiSinhChanged();
    partial void OnMaLopChanging(string value);
    partial void OnMaLopChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnSdtChanging(string value);
    partial void OnSdtChanged();
    partial void OnDiaChiChanging(string value);
    partial void OnDiaChiChanged();
    #endregion
		
		public SinhVien()
		{
			this._Lop = default(EntityRef<Lop>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaSV", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaSV
		{
			get
			{
				return this._MaSV;
			}
			set
			{
				if ((this._MaSV != value))
				{
					this.OnMaSVChanging(value);
					this.SendPropertyChanging();
					this._MaSV = value;
					this.SendPropertyChanged("MaSV");
					this.OnMaSVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoTen", DbType="NChar(50)")]
		public string HoTen
		{
			get
			{
				return this._HoTen;
			}
			set
			{
				if ((this._HoTen != value))
				{
					this.OnHoTenChanging(value);
					this.SendPropertyChanging();
					this._HoTen = value;
					this.SendPropertyChanged("HoTen");
					this.OnHoTenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgaySinh", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgaySinh
		{
			get
			{
				return this._NgaySinh;
			}
			set
			{
				if ((this._NgaySinh != value))
				{
					this.OnNgaySinhChanging(value);
					this.SendPropertyChanging();
					this._NgaySinh = value;
					this.SendPropertyChanged("NgaySinh");
					this.OnNgaySinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GioiTinh", DbType="Int")]
		public System.Nullable<int> GioiTinh
		{
			get
			{
				return this._GioiTinh;
			}
			set
			{
				if ((this._GioiTinh != value))
				{
					this.OnGioiTinhChanging(value);
					this.SendPropertyChanging();
					this._GioiTinh = value;
					this.SendPropertyChanged("GioiTinh");
					this.OnGioiTinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DanToc", DbType="NVarChar(50)")]
		public string DanToc
		{
			get
			{
				return this._DanToc;
			}
			set
			{
				if ((this._DanToc != value))
				{
					this.OnDanTocChanging(value);
					this.SendPropertyChanging();
					this._DanToc = value;
					this.SendPropertyChanged("DanToc");
					this.OnDanTocChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoiSinh", DbType="NVarChar(100)")]
		public string NoiSinh
		{
			get
			{
				return this._NoiSinh;
			}
			set
			{
				if ((this._NoiSinh != value))
				{
					this.OnNoiSinhChanging(value);
					this.SendPropertyChanging();
					this._NoiSinh = value;
					this.SendPropertyChanged("NoiSinh");
					this.OnNoiSinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaLop", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string MaLop
		{
			get
			{
				return this._MaLop;
			}
			set
			{
				if ((this._MaLop != value))
				{
					if (this._Lop.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaLopChanging(value);
					this.SendPropertyChanging();
					this._MaLop = value;
					this.SendPropertyChanged("MaLop");
					this.OnMaLopChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(50)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sdt", DbType="NVarChar(50)")]
		public string Sdt
		{
			get
			{
				return this._Sdt;
			}
			set
			{
				if ((this._Sdt != value))
				{
					this.OnSdtChanging(value);
					this.SendPropertyChanging();
					this._Sdt = value;
					this.SendPropertyChanged("Sdt");
					this.OnSdtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaChi", DbType="NVarChar(100)")]
		public string DiaChi
		{
			get
			{
				return this._DiaChi;
			}
			set
			{
				if ((this._DiaChi != value))
				{
					this.OnDiaChiChanging(value);
					this.SendPropertyChanging();
					this._DiaChi = value;
					this.SendPropertyChanged("DiaChi");
					this.OnDiaChiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Lop_SinhVien", Storage="_Lop", ThisKey="MaLop", OtherKey="MaLop", IsForeignKey=true)]
		public Lop Lop
		{
			get
			{
				return this._Lop.Entity;
			}
			set
			{
				Lop previousValue = this._Lop.Entity;
				if (((previousValue != value) 
							|| (this._Lop.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Lop.Entity = null;
						previousValue.SinhViens.Remove(this);
					}
					this._Lop.Entity = value;
					if ((value != null))
					{
						value.SinhViens.Add(this);
						this._MaLop = value.MaLop;
					}
					else
					{
						this._MaLop = default(string);
					}
					this.SendPropertyChanged("Lop");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DangNhap")]
	public partial class DangNhap
	{
		
		private string _username;
		
		private string _password;
		
		public DangNhap()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_username", DbType="NVarChar(50)")]
		public string username
		{
			get
			{
				return this._username;
			}
			set
			{
				if ((this._username != value))
				{
					this._username = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_password", DbType="NVarChar(50)")]
		public string password
		{
			get
			{
				return this._password;
			}
			set
			{
				if ((this._password != value))
				{
					this._password = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Ketqua")]
	public partial class Ketqua
	{
		
		private string _MaSV;
		
		private string _HoTen;
		
		private string _MaLop;
		
		private string _MaHP;
		
		private System.Nullable<double> _DiemCC;
		
		private System.Nullable<double> _DiemGK;
		
		private System.Nullable<double> _DiemCK;
		
		private System.Nullable<double> _DiemHP;
		
		private string _DiemChu;
		
		private System.Nullable<int> _DiemSo;
		
		private string _TenHP;
		
		public Ketqua()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaSV", DbType="NVarChar(50)")]
		public string MaSV
		{
			get
			{
				return this._MaSV;
			}
			set
			{
				if ((this._MaSV != value))
				{
					this._MaSV = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoTen", DbType="NChar(50)")]
		public string HoTen
		{
			get
			{
				return this._HoTen;
			}
			set
			{
				if ((this._HoTen != value))
				{
					this._HoTen = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaLop", DbType="NVarChar(50)")]
		public string MaLop
		{
			get
			{
				return this._MaLop;
			}
			set
			{
				if ((this._MaLop != value))
				{
					this._MaLop = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaHP", DbType="NVarChar(50)")]
		public string MaHP
		{
			get
			{
				return this._MaHP;
			}
			set
			{
				if ((this._MaHP != value))
				{
					this._MaHP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiemCC", DbType="Float")]
		public System.Nullable<double> DiemCC
		{
			get
			{
				return this._DiemCC;
			}
			set
			{
				if ((this._DiemCC != value))
				{
					this._DiemCC = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiemGK", DbType="Float")]
		public System.Nullable<double> DiemGK
		{
			get
			{
				return this._DiemGK;
			}
			set
			{
				if ((this._DiemGK != value))
				{
					this._DiemGK = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiemCK", DbType="Float")]
		public System.Nullable<double> DiemCK
		{
			get
			{
				return this._DiemCK;
			}
			set
			{
				if ((this._DiemCK != value))
				{
					this._DiemCK = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiemHP", DbType="Float")]
		public System.Nullable<double> DiemHP
		{
			get
			{
				return this._DiemHP;
			}
			set
			{
				if ((this._DiemHP != value))
				{
					this._DiemHP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiemChu", DbType="NChar(10)")]
		public string DiemChu
		{
			get
			{
				return this._DiemChu;
			}
			set
			{
				if ((this._DiemChu != value))
				{
					this._DiemChu = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiemSo", DbType="Int")]
		public System.Nullable<int> DiemSo
		{
			get
			{
				return this._DiemSo;
			}
			set
			{
				if ((this._DiemSo != value))
				{
					this._DiemSo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenHP", DbType="NVarChar(100)")]
		public string TenHP
		{
			get
			{
				return this._TenHP;
			}
			set
			{
				if ((this._TenHP != value))
				{
					this._TenHP = value;
				}
			}
		}
	}
	
	public partial class BangdiemHPResult
	{
		
		private string _MaSV;
		
		private string _HoTen;
		
		private System.Nullable<System.DateTime> _NgaySinh;
		
		private System.Nullable<double> _DiemCC;
		
		private System.Nullable<double> _DiemGK;
		
		private System.Nullable<double> _DiemCK;
		
		public BangdiemHPResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaSV", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string MaSV
		{
			get
			{
				return this._MaSV;
			}
			set
			{
				if ((this._MaSV != value))
				{
					this._MaSV = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoTen", DbType="NChar(50)")]
		public string HoTen
		{
			get
			{
				return this._HoTen;
			}
			set
			{
				if ((this._HoTen != value))
				{
					this._HoTen = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgaySinh", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgaySinh
		{
			get
			{
				return this._NgaySinh;
			}
			set
			{
				if ((this._NgaySinh != value))
				{
					this._NgaySinh = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiemCC", DbType="Float")]
		public System.Nullable<double> DiemCC
		{
			get
			{
				return this._DiemCC;
			}
			set
			{
				if ((this._DiemCC != value))
				{
					this._DiemCC = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiemGK", DbType="Float")]
		public System.Nullable<double> DiemGK
		{
			get
			{
				return this._DiemGK;
			}
			set
			{
				if ((this._DiemGK != value))
				{
					this._DiemGK = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiemCK", DbType="Float")]
		public System.Nullable<double> DiemCK
		{
			get
			{
				return this._DiemCK;
			}
			set
			{
				if ((this._DiemCK != value))
				{
					this._DiemCK = value;
				}
			}
		}
	}
	
	public partial class DiemHP_SearchResult
	{
		
		private string _MaSV;
		
		private string _MaHP;
		
		private System.Nullable<double> _DiemCC;
		
		private System.Nullable<double> _DiemGK;
		
		private System.Nullable<double> _DiemCK;
		
		public DiemHP_SearchResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaSV", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string MaSV
		{
			get
			{
				return this._MaSV;
			}
			set
			{
				if ((this._MaSV != value))
				{
					this._MaSV = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaHP", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string MaHP
		{
			get
			{
				return this._MaHP;
			}
			set
			{
				if ((this._MaHP != value))
				{
					this._MaHP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiemCC", DbType="Float")]
		public System.Nullable<double> DiemCC
		{
			get
			{
				return this._DiemCC;
			}
			set
			{
				if ((this._DiemCC != value))
				{
					this._DiemCC = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiemGK", DbType="Float")]
		public System.Nullable<double> DiemGK
		{
			get
			{
				return this._DiemGK;
			}
			set
			{
				if ((this._DiemGK != value))
				{
					this._DiemGK = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiemCK", DbType="Float")]
		public System.Nullable<double> DiemCK
		{
			get
			{
				return this._DiemCK;
			}
			set
			{
				if ((this._DiemCK != value))
				{
					this._DiemCK = value;
				}
			}
		}
	}
	
	public partial class HocKy_SelectAllResult
	{
		
		private string _MaHocKy;
		
		private string _TenHocKy;
		
		public HocKy_SelectAllResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaHocKy", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string MaHocKy
		{
			get
			{
				return this._MaHocKy;
			}
			set
			{
				if ((this._MaHocKy != value))
				{
					this._MaHocKy = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenHocKy", DbType="NVarChar(100)")]
		public string TenHocKy
		{
			get
			{
				return this._TenHocKy;
			}
			set
			{
				if ((this._TenHocKy != value))
				{
					this._TenHocKy = value;
				}
			}
		}
	}
	
	public partial class Lops_SelectAllResult
	{
		
		private string _MaLop;
		
		private string _TenLop;
		
		private string _GiaoVienChuNhiem;
		
		private string _Khoa;
		
		public Lops_SelectAllResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaLop", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string MaLop
		{
			get
			{
				return this._MaLop;
			}
			set
			{
				if ((this._MaLop != value))
				{
					this._MaLop = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenLop", DbType="NVarChar(100)")]
		public string TenLop
		{
			get
			{
				return this._TenLop;
			}
			set
			{
				if ((this._TenLop != value))
				{
					this._TenLop = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GiaoVienChuNhiem", DbType="NVarChar(50)")]
		public string GiaoVienChuNhiem
		{
			get
			{
				return this._GiaoVienChuNhiem;
			}
			set
			{
				if ((this._GiaoVienChuNhiem != value))
				{
					this._GiaoVienChuNhiem = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Khoa", DbType="NVarChar(50)")]
		public string Khoa
		{
			get
			{
				return this._Khoa;
			}
			set
			{
				if ((this._Khoa != value))
				{
					this._Khoa = value;
				}
			}
		}
	}
	
	public partial class MonHP_SelectAllResult
	{
		
		private string _MaHP;
		
		private string _TenHP;
		
		private System.Nullable<int> _SoTinChi;
		
		private string _MaHocKy;
		
		public MonHP_SelectAllResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaHP", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string MaHP
		{
			get
			{
				return this._MaHP;
			}
			set
			{
				if ((this._MaHP != value))
				{
					this._MaHP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenHP", DbType="NVarChar(100)")]
		public string TenHP
		{
			get
			{
				return this._TenHP;
			}
			set
			{
				if ((this._TenHP != value))
				{
					this._TenHP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoTinChi", DbType="Int")]
		public System.Nullable<int> SoTinChi
		{
			get
			{
				return this._SoTinChi;
			}
			set
			{
				if ((this._SoTinChi != value))
				{
					this._SoTinChi = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaHocKy", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string MaHocKy
		{
			get
			{
				return this._MaHocKy;
			}
			set
			{
				if ((this._MaHocKy != value))
				{
					this._MaHocKy = value;
				}
			}
		}
	}
	
	public partial class MonHP_SelectMaHocKyResult
	{
		
		private string _MaHP;
		
		private string _TenHP;
		
		private System.Nullable<int> _SoTinChi;
		
		private string _MaHocKy;
		
		public MonHP_SelectMaHocKyResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaHP", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string MaHP
		{
			get
			{
				return this._MaHP;
			}
			set
			{
				if ((this._MaHP != value))
				{
					this._MaHP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenHP", DbType="NVarChar(100)")]
		public string TenHP
		{
			get
			{
				return this._TenHP;
			}
			set
			{
				if ((this._TenHP != value))
				{
					this._TenHP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoTinChi", DbType="Int")]
		public System.Nullable<int> SoTinChi
		{
			get
			{
				return this._SoTinChi;
			}
			set
			{
				if ((this._SoTinChi != value))
				{
					this._SoTinChi = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaHocKy", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string MaHocKy
		{
			get
			{
				return this._MaHocKy;
			}
			set
			{
				if ((this._MaHocKy != value))
				{
					this._MaHocKy = value;
				}
			}
		}
	}
	
	public partial class SinhVien_SearchResult
	{
		
		private string _MaSV;
		
		private string _HoTen;
		
		private System.Nullable<System.DateTime> _NgaySinh;
		
		private System.Nullable<int> _GioiTinh;
		
		private string _DanToc;
		
		private string _NoiSinh;
		
		private string _MaLop;
		
		private string _Email;
		
		private string _Sdt;
		
		private string _DiaChi;
		
		public SinhVien_SearchResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaSV", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string MaSV
		{
			get
			{
				return this._MaSV;
			}
			set
			{
				if ((this._MaSV != value))
				{
					this._MaSV = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoTen", DbType="NChar(50)")]
		public string HoTen
		{
			get
			{
				return this._HoTen;
			}
			set
			{
				if ((this._HoTen != value))
				{
					this._HoTen = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgaySinh", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgaySinh
		{
			get
			{
				return this._NgaySinh;
			}
			set
			{
				if ((this._NgaySinh != value))
				{
					this._NgaySinh = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GioiTinh", DbType="Int")]
		public System.Nullable<int> GioiTinh
		{
			get
			{
				return this._GioiTinh;
			}
			set
			{
				if ((this._GioiTinh != value))
				{
					this._GioiTinh = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DanToc", DbType="NVarChar(50)")]
		public string DanToc
		{
			get
			{
				return this._DanToc;
			}
			set
			{
				if ((this._DanToc != value))
				{
					this._DanToc = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoiSinh", DbType="NVarChar(100)")]
		public string NoiSinh
		{
			get
			{
				return this._NoiSinh;
			}
			set
			{
				if ((this._NoiSinh != value))
				{
					this._NoiSinh = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaLop", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string MaLop
		{
			get
			{
				return this._MaLop;
			}
			set
			{
				if ((this._MaLop != value))
				{
					this._MaLop = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(50)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this._Email = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sdt", DbType="NVarChar(50)")]
		public string Sdt
		{
			get
			{
				return this._Sdt;
			}
			set
			{
				if ((this._Sdt != value))
				{
					this._Sdt = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaChi", DbType="NVarChar(100)")]
		public string DiaChi
		{
			get
			{
				return this._DiaChi;
			}
			set
			{
				if ((this._DiaChi != value))
				{
					this._DiaChi = value;
				}
			}
		}
	}
	
	public partial class SinhVien_SelectAllResult
	{
		
		private string _MaSV;
		
		private string _HoTen;
		
		private System.Nullable<System.DateTime> _NgaySinh;
		
		private System.Nullable<int> _GioiTinh;
		
		private string _DanToc;
		
		private string _NoiSinh;
		
		private string _MaLop;
		
		private string _Email;
		
		private string _Sdt;
		
		private string _DiaChi;
		
		public SinhVien_SelectAllResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaSV", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string MaSV
		{
			get
			{
				return this._MaSV;
			}
			set
			{
				if ((this._MaSV != value))
				{
					this._MaSV = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoTen", DbType="NChar(50)")]
		public string HoTen
		{
			get
			{
				return this._HoTen;
			}
			set
			{
				if ((this._HoTen != value))
				{
					this._HoTen = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgaySinh", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgaySinh
		{
			get
			{
				return this._NgaySinh;
			}
			set
			{
				if ((this._NgaySinh != value))
				{
					this._NgaySinh = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GioiTinh", DbType="Int")]
		public System.Nullable<int> GioiTinh
		{
			get
			{
				return this._GioiTinh;
			}
			set
			{
				if ((this._GioiTinh != value))
				{
					this._GioiTinh = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DanToc", DbType="NVarChar(50)")]
		public string DanToc
		{
			get
			{
				return this._DanToc;
			}
			set
			{
				if ((this._DanToc != value))
				{
					this._DanToc = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoiSinh", DbType="NVarChar(100)")]
		public string NoiSinh
		{
			get
			{
				return this._NoiSinh;
			}
			set
			{
				if ((this._NoiSinh != value))
				{
					this._NoiSinh = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaLop", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string MaLop
		{
			get
			{
				return this._MaLop;
			}
			set
			{
				if ((this._MaLop != value))
				{
					this._MaLop = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(50)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this._Email = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sdt", DbType="NVarChar(50)")]
		public string Sdt
		{
			get
			{
				return this._Sdt;
			}
			set
			{
				if ((this._Sdt != value))
				{
					this._Sdt = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaChi", DbType="NVarChar(100)")]
		public string DiaChi
		{
			get
			{
				return this._DiaChi;
			}
			set
			{
				if ((this._DiaChi != value))
				{
					this._DiaChi = value;
				}
			}
		}
	}
	
	public partial class SinhVien_selectMalopResult
	{
		
		private string _MaSV;
		
		private string _HoTen;
		
		private System.Nullable<System.DateTime> _NgaySinh;
		
		private System.Nullable<int> _GioiTinh;
		
		private string _DanToc;
		
		private string _NoiSinh;
		
		private string _MaLop;
		
		private string _Email;
		
		private string _Sdt;
		
		private string _DiaChi;
		
		public SinhVien_selectMalopResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaSV", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string MaSV
		{
			get
			{
				return this._MaSV;
			}
			set
			{
				if ((this._MaSV != value))
				{
					this._MaSV = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoTen", DbType="NChar(50)")]
		public string HoTen
		{
			get
			{
				return this._HoTen;
			}
			set
			{
				if ((this._HoTen != value))
				{
					this._HoTen = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgaySinh", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgaySinh
		{
			get
			{
				return this._NgaySinh;
			}
			set
			{
				if ((this._NgaySinh != value))
				{
					this._NgaySinh = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GioiTinh", DbType="Int")]
		public System.Nullable<int> GioiTinh
		{
			get
			{
				return this._GioiTinh;
			}
			set
			{
				if ((this._GioiTinh != value))
				{
					this._GioiTinh = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DanToc", DbType="NVarChar(50)")]
		public string DanToc
		{
			get
			{
				return this._DanToc;
			}
			set
			{
				if ((this._DanToc != value))
				{
					this._DanToc = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoiSinh", DbType="NVarChar(100)")]
		public string NoiSinh
		{
			get
			{
				return this._NoiSinh;
			}
			set
			{
				if ((this._NoiSinh != value))
				{
					this._NoiSinh = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaLop", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string MaLop
		{
			get
			{
				return this._MaLop;
			}
			set
			{
				if ((this._MaLop != value))
				{
					this._MaLop = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(50)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this._Email = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sdt", DbType="NVarChar(50)")]
		public string Sdt
		{
			get
			{
				return this._Sdt;
			}
			set
			{
				if ((this._Sdt != value))
				{
					this._Sdt = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaChi", DbType="NVarChar(100)")]
		public string DiaChi
		{
			get
			{
				return this._DiaChi;
			}
			set
			{
				if ((this._DiaChi != value))
				{
					this._DiaChi = value;
				}
			}
		}
	}
	
	public partial class Sinhvien_selectMalopsResult
	{
		
		private string _MaSV;
		
		private string _HoTen;
		
		private System.Nullable<System.DateTime> _NgaySinh;
		
		private System.Nullable<int> _GioiTinh;
		
		private string _DanToc;
		
		private string _NoiSinh;
		
		private string _MaLop;
		
		private string _Email;
		
		private string _Sdt;
		
		private string _DiaChi;
		
		public Sinhvien_selectMalopsResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaSV", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string MaSV
		{
			get
			{
				return this._MaSV;
			}
			set
			{
				if ((this._MaSV != value))
				{
					this._MaSV = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoTen", DbType="NChar(50)")]
		public string HoTen
		{
			get
			{
				return this._HoTen;
			}
			set
			{
				if ((this._HoTen != value))
				{
					this._HoTen = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgaySinh", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgaySinh
		{
			get
			{
				return this._NgaySinh;
			}
			set
			{
				if ((this._NgaySinh != value))
				{
					this._NgaySinh = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GioiTinh", DbType="Int")]
		public System.Nullable<int> GioiTinh
		{
			get
			{
				return this._GioiTinh;
			}
			set
			{
				if ((this._GioiTinh != value))
				{
					this._GioiTinh = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DanToc", DbType="NVarChar(50)")]
		public string DanToc
		{
			get
			{
				return this._DanToc;
			}
			set
			{
				if ((this._DanToc != value))
				{
					this._DanToc = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoiSinh", DbType="NVarChar(100)")]
		public string NoiSinh
		{
			get
			{
				return this._NoiSinh;
			}
			set
			{
				if ((this._NoiSinh != value))
				{
					this._NoiSinh = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaLop", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string MaLop
		{
			get
			{
				return this._MaLop;
			}
			set
			{
				if ((this._MaLop != value))
				{
					this._MaLop = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(50)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this._Email = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sdt", DbType="NVarChar(50)")]
		public string Sdt
		{
			get
			{
				return this._Sdt;
			}
			set
			{
				if ((this._Sdt != value))
				{
					this._Sdt = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaChi", DbType="NVarChar(100)")]
		public string DiaChi
		{
			get
			{
				return this._DiaChi;
			}
			set
			{
				if ((this._DiaChi != value))
				{
					this._DiaChi = value;
				}
			}
		}
	}
	
	public partial class Sinhvien_selectMasvResult
	{
		
		private string _MaSV;
		
		private string _HoTen;
		
		private System.Nullable<System.DateTime> _NgaySinh;
		
		private System.Nullable<int> _GioiTinh;
		
		private string _DanToc;
		
		private string _NoiSinh;
		
		private string _MaLop;
		
		private string _Email;
		
		private string _Sdt;
		
		private string _DiaChi;
		
		public Sinhvien_selectMasvResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaSV", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string MaSV
		{
			get
			{
				return this._MaSV;
			}
			set
			{
				if ((this._MaSV != value))
				{
					this._MaSV = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoTen", DbType="NChar(50)")]
		public string HoTen
		{
			get
			{
				return this._HoTen;
			}
			set
			{
				if ((this._HoTen != value))
				{
					this._HoTen = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgaySinh", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgaySinh
		{
			get
			{
				return this._NgaySinh;
			}
			set
			{
				if ((this._NgaySinh != value))
				{
					this._NgaySinh = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GioiTinh", DbType="Int")]
		public System.Nullable<int> GioiTinh
		{
			get
			{
				return this._GioiTinh;
			}
			set
			{
				if ((this._GioiTinh != value))
				{
					this._GioiTinh = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DanToc", DbType="NVarChar(50)")]
		public string DanToc
		{
			get
			{
				return this._DanToc;
			}
			set
			{
				if ((this._DanToc != value))
				{
					this._DanToc = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoiSinh", DbType="NVarChar(100)")]
		public string NoiSinh
		{
			get
			{
				return this._NoiSinh;
			}
			set
			{
				if ((this._NoiSinh != value))
				{
					this._NoiSinh = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaLop", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string MaLop
		{
			get
			{
				return this._MaLop;
			}
			set
			{
				if ((this._MaLop != value))
				{
					this._MaLop = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(50)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this._Email = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sdt", DbType="NVarChar(50)")]
		public string Sdt
		{
			get
			{
				return this._Sdt;
			}
			set
			{
				if ((this._Sdt != value))
				{
					this._Sdt = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaChi", DbType="NVarChar(100)")]
		public string DiaChi
		{
			get
			{
				return this._DiaChi;
			}
			set
			{
				if ((this._DiaChi != value))
				{
					this._DiaChi = value;
				}
			}
		}
	}
	
	public partial class ketqua_selectAllResult
	{
		
		private string _MaSV;
		
		private string _HoTen;
		
		private string _MaLop;
		
		private string _MaHP;
		
		private System.Nullable<double> _DiemCC;
		
		private System.Nullable<double> _DiemGK;
		
		private System.Nullable<double> _DiemCK;
		
		private System.Nullable<double> _DiemHP;
		
		private string _DiemChu;
		
		private System.Nullable<int> _DiemSo;
		
		private string _TenHP;
		
		public ketqua_selectAllResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaSV", DbType="NVarChar(50)")]
		public string MaSV
		{
			get
			{
				return this._MaSV;
			}
			set
			{
				if ((this._MaSV != value))
				{
					this._MaSV = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoTen", DbType="NChar(50)")]
		public string HoTen
		{
			get
			{
				return this._HoTen;
			}
			set
			{
				if ((this._HoTen != value))
				{
					this._HoTen = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaLop", DbType="NVarChar(50)")]
		public string MaLop
		{
			get
			{
				return this._MaLop;
			}
			set
			{
				if ((this._MaLop != value))
				{
					this._MaLop = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaHP", DbType="NVarChar(50)")]
		public string MaHP
		{
			get
			{
				return this._MaHP;
			}
			set
			{
				if ((this._MaHP != value))
				{
					this._MaHP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiemCC", DbType="Float")]
		public System.Nullable<double> DiemCC
		{
			get
			{
				return this._DiemCC;
			}
			set
			{
				if ((this._DiemCC != value))
				{
					this._DiemCC = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiemGK", DbType="Float")]
		public System.Nullable<double> DiemGK
		{
			get
			{
				return this._DiemGK;
			}
			set
			{
				if ((this._DiemGK != value))
				{
					this._DiemGK = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiemCK", DbType="Float")]
		public System.Nullable<double> DiemCK
		{
			get
			{
				return this._DiemCK;
			}
			set
			{
				if ((this._DiemCK != value))
				{
					this._DiemCK = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiemHP", DbType="Float")]
		public System.Nullable<double> DiemHP
		{
			get
			{
				return this._DiemHP;
			}
			set
			{
				if ((this._DiemHP != value))
				{
					this._DiemHP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiemChu", DbType="NChar(10)")]
		public string DiemChu
		{
			get
			{
				return this._DiemChu;
			}
			set
			{
				if ((this._DiemChu != value))
				{
					this._DiemChu = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiemSo", DbType="Int")]
		public System.Nullable<int> DiemSo
		{
			get
			{
				return this._DiemSo;
			}
			set
			{
				if ((this._DiemSo != value))
				{
					this._DiemSo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenHP", DbType="NVarChar(100)")]
		public string TenHP
		{
			get
			{
				return this._TenHP;
			}
			set
			{
				if ((this._TenHP != value))
				{
					this._TenHP = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
